Error calling workflow: 'build_and_fetch_logs'
Error calling job: 'build'
Cannot find a definition for command named store_artifact  # See the Python orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Download Android SDK
          command: |
            sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: nextdns-manager.apk

  fetch_nextdns_logs:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install requests
      - run:
          name: Fetch NextDNS logs
          command: |
            . venv/bin/activate
            python - <<EOF
            import requests
            import json
            from datetime import datetime

            def fetch_nextdns_logs():
                url = 'https://api.nextdns.io/profiles/85d564/logs'
                headers = {'X-Api-Key': 'f31f2871d328a52a45fefadc09a1c67d0dd5d53d'}
                response = requests.get(url, headers=headers)
                if response.status_code == 200:
                    return response.json()
                else:
                    raise Exception("Erro ao buscar logs: " + response.text)

            logs = fetch_nextdns_logs()
            
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f'nextdns_logs_{timestamp}.json'
            
            with open(filename, 'w') as f:
                json.dump(logs, f, indent=2)
            
            print(f"Logs salvos em {filename}")
            EOF
      - store_artifacts:
          path: nextdns_logs_*.json
          destination: nextdns_logs

workflows:
  version: 2
  build_and_fetch_logs:
    jobs:
      - build
      - fetch_nextdns_logs      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test